AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambdahelloworld
  Sample SAM Template for lambdahelloworld

Globals:
  Function:
    Timeout: 20

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./HelloWorldFunction/target/hello-world-lambad.zip
      Handler: helloworld.App::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          REGION: eu-west-2
          LOG_LEVEL: DEBUG
          Q_PROFILE: local

Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  HelloWorldPseudoParameters:
    Description: Pseudo parameter output value
    Value: !Join
      - ',  '
      - - !Ref AWS::Region
        - !Ref AWS::Region
#        - 'Account: ' !Ref AWS::AccountId
#        - 'StackName: ' !Ref AWS::StackName


