AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: HelloPojo

Resources:

  HelloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloPojo
      Runtime: java8
      MemorySize: 512
      Handler: com.bskyb.aws.lambda.HelloPojo::handler
      CodeUri: target/lambda.jar
