AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-to-s3
  JS lambda-to-s3 
Globals:
  Function:
    Timeout: 20

Resources:
#  s3 bucket resource
  FileContentBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: js-lambda-to-s3-bucket

#  lambda funcation resouce
  LambdaToS3:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: LambdaToS3
      Handler: com.bskyb.aws.poc.lambdatos3.App::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          ENV_BUCKET_NAME: !Ref FileContentBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref FileContentBucket
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LambdaToS3:
    Description: "Lambda function to write into s3 bucket"
    Value: !GetAtt LambdaToS3.Arn
  LambdaToS3IamRole:
    Description: "Implicit IAM Role created for lambdatos3 function"
    Value: !GetAtt LambdaToS3Role.Arn
